Repository PastVu/pastvu, pull requests merged in 2020-11, with the labels that each got.

#256 Create stale.yml
  .github/workflows/stale.yml
Labels: Collaboration

#253 Add initial test task to run eslint.
  Gruntfile.js
  package-lock.json
  package.json
Labels: CI/CD

#255 Create node.js.yml
  .github/workflows/node.js.yml
Labels: CI/CD, Infrastructure

#260 Add Google and Yandex Maps API key support / Добавить поддержку API ключа для сервисов Google и Yandex карт
  config/default.config.js
  controllers/settings.js
  public/js/Params.js
  public/js/_mainConfig.js
  public/js/lib/leaflet/extends/L.Google.js
  public/js/lib/leaflet/extends/L.Yandex.js
  public/js/lib/leaflet/plugins/Google.js
  public/js/lib/leaflet/plugins/Yandex.js
  public/js/module/map/map.js
  public/js/module/map/mapClusterCalc.js
  public/js/module/map/navSlider.js
Labels: API, Map

#254 Configure Docker image CI
  .github/workflows/docker-image.yml
Labels: CI/CD, Infrastructure

#194 Fixing issue 162 — "Share this photo" dialog upgrade
  public/js/module/common/share.js
  public/js/module/photo/photo.js
Labels: UI, UX/Design

#264 Automerge 'master' to 'en'
  .github/workflows/en-automerge.yml
Labels: Automation

#270 Replace Google layer with most current implementation / Заменить слой Гугла на более новый
  public/js/lib/leaflet/extends/L.Google.js
  public/js/lib/leaflet/plugins/Google.js
  public/js/module/map/map.js
  public/js/module/map/mapClusterCalc.js
Labels: Map

#265 Start adding public/js content to eslint / Начать добавлять клиентский код в eslint
  .eslintignore
  .eslintrc.js
  Gruntfile.js
  public/js/lib/leaflet/extends/L.Google.js
  public/js/lib/leaflet/extends/L.Yandex.js
  public/js/lib/leaflet/extends/L.neoMap.js
Labels: Automation, CI/CD, Tests

#284 Expand linting to regionCheck
  Gruntfile.js
  public/js/module/admin/regionCheck.js
Labels: Admin, CI/CD

#298 Add debugging instruction.
  README.md
  package.json
Labels: Debug

#307 MongoDB 4.x migration - Part 1
  README.md
  controllers/_session.js
  controllers/apilog.js
  controllers/auth.js
  controllers/cluster.js
  controllers/comment.js
  controllers/connection.js
  controllers/converter.js
  controllers/index.js
  controllers/photo.js
  controllers/region.js
  controllers/subscr.js
  controllers/systemjs.js
  controllers/userobjectrel.js
  docker-compose.yml
  models/User.js
  models/pagination.js
  package-lock.json
  package.json
Labels: Todo, dependencies

#297 Manage notifications in config
  config/default.config.js
  config/local.config.js.docker-example
  config/local.config.js.example
  controllers/subscr.js
  docker-compose.yml
Labels: Mail, Notifications, backend
