Repository PastVu/pastvu, pull requests merged in 2020-10, with the labels that each got.

#193 Issue 163 — Restore browser image options ("Save image as..." etc) for main image area
  public/style/photo/photo.less
  views/module/photo/photo.pug
Labels: UI, UX/Design

#192 Moving action buttons below a image
  public/style/photo/photo.less
  views/module/photo/photo.pug
Labels: UX/Design

#206 Respect minZoom map layer setting | Учитывать значение minZoom из параметров слоя
  public/js/module/map/map.js
Labels: Bug, Map
